version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - collatz_data:/data
    environment:
      - FLASK_APP=wsgi.py
      - FLASK_ENV=development

volumes:
  collatz_data: